Repository openshift/vertical-pod-autoscaler-operator, pull requests merged in 2020-10, with the labels that each got.

#36 Bug 1884413: Update manifests to pass validation and allow direct upgrades
  manifests/4.6/vertical-pod-autoscaler.v4.6.0.clusterserviceversion.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#39 bug 1886200: manifests/art.yaml: CSV name is verticalpodautoscaler
  manifests/art.yaml
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#38 bug 1882524: [release-4.6] manifests/art.yaml: CSV name is verticalpodautoscaler
  manifests/art.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, group-lead-approved, lgtm

#41 Add bugzilla component to OWNERS file
  OWNERS
Labels: approved

#43 Bug 1885213: Add support for deploymentconfigs to VPA
  manifests/4.6/vertical-pod-autoscaler.v4.6.0.clusterserviceversion.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
