Repository openshift/vertical-pod-autoscaler-operator, pull requests merged in 2024-12, with the labels that each got.

#187 OCPBUGS-45146: [release-4.18] OWNERS: Remove John Kyros, add Max Cao
  OWNERS
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#189 OCPBUGS-45148: [release-4.16] OWNERS: Remove John Kyros, add Max Cao
  OWNERS
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#190 OCPBUGS-45149: [release-4.15] OWNERS: Remove Seth & Ryan, add Max Cao
  OWNERS
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#191 OCPBUGS-45150: [release-4.14] OWNERS: Remove Seth & Ryan, add Max Cao
  OWNERS
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#192 OCPBUGS-45151: [release-4.13] OWNERS: Remove Seth & Ryan, add Max Cao
  OWNERS
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#193 OCPBUGS-45152: [release-4.12] OWNERS: Remove Seth & Ryan, add Max Cao
  OWNERS
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#178 OCPBUGS-45372: Update default resource requests and QPS/Burst
  Makefile
  bundle/manifests/vertical-pod-autoscaler.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/vertical-pod-autoscaler.clusterserviceversion.yaml
  internal/controller/verticalpodautoscaler/admission_plugin.go
  internal/controller/verticalpodautoscaler/verticalpodautoscaler_controller.go
  internal/controller/verticalpodautoscaler/verticalpodautoscaler_controller_test.go
  internal/util/util.go
  internal/util/util_test.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#197 PODAUTO-284: Add CI checks to ensure "make bundle/generate" before pushing
  Makefile
Labels: lgtm, approved, jira/valid-reference

#198 OCPBUGS-45521: Remove unnecessary initialization-resource CSV annotation
  Makefile
  bundle/manifests/vertical-pod-autoscaler.clusterserviceversion.yaml
  config/manifests/bases/vertical-pod-autoscaler.clusterserviceversion.yaml
  config/olm-catalog/vpa-subscription.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#199 Clean old bundles before regenerating
  Makefile
Labels: lgtm, approved
